apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omni-ava.configMapName" . }}
  namespace: {{ include "omni-ava.namespace" . }}
  labels:
    {{- include "omni-ava.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.app }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
