"""
Mercury Agent ♱
Copyright (C) 2025 Steel Security Advisory LLC

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see https://www.gnu.org/licenses/.
"""

from __future__ import annotations


"""
Predictive Coding Module for Mercury Agent.

Implements neuroscience-inspired predictive coding for anomaly detection,
based on:
- "Predictive Coding" (Rao & Ballard, 1999)
- "The Free Energy Principle" (Friston, 2010)
- "Hierarchical Predictive Coding" (Spratling, 2017)
- "Active Inference for Anomaly Detection" (Parr & Friston, 2019)

Predictive coding theory suggests the brain minimizes prediction errors
by maintaining hierarchical generative models that predict sensory input.
Anomalies correspond to large prediction errors that cannot be explained
away.

Key Concepts:
- Prediction: Generate expected observations
- Prediction Error: Difference between prediction and observation
- Precision Weighting: Confidence in predictions
- Hierarchical Processing: Multi-level predictions
- Active Inference: Action selection to minimize surprise

This module uses these principles for biologically-inspired
anomaly detection in Mercury Agent.
"""

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import numpy as np


logger = logging.getLogger(__name__)


# =============================================================================
# Constants
# =============================================================================

PHI = (1 + np.sqrt(5)) / 2  # Golden ratio

# Predictive coding parameters
DEFAULT_LEARNING_RATE = 0.01
DEFAULT_PRECISION = 1.0
MAX_HIERARCHY_DEPTH = 5
PREDICTION_HORIZON = 10


class ProcessingLevel(Enum):
    """Levels in the predictive hierarchy."""

    SENSORY = "sensory"  # Raw sensory data
    FEATURE = "feature"  # Feature extraction
    OBJECT = "object"  # Object recognition
    CONTEXT = "context"  # Contextual understanding
    ABSTRACT = "abstract"  # Abstract concepts


class UpdateMode(Enum):
    """Modes for belief updating."""

    PREDICTIVE = "predictive"  # Standard predictive coding
    ACTIVE = "active"  # Active inference
    HIERARCHICAL = "hierarchical"  # Hierarchical updates
    FREE_ENERGY = "free_energy"  # Free energy minimization


class PredictionType(Enum):
    """Types of predictions."""

    STATE = "state"  # State prediction
    OBSERVATION = "observation"  # Observation prediction
    ACTION = "action"  # Action prediction
    PRECISION = "precision"  # Precision prediction


# =============================================================================
# Data Structures
# =============================================================================


@dataclass
class Prediction:
    """A prediction generated by the model.

    Attributes:
        prediction_id: Unique identifier
        prediction_type: Type of prediction
        level: Processing level
        value: Predicted value(s)
        precision: Confidence/precision of prediction
        timestamp: Generation timestamp
        metadata: Additional metadata
    """

    prediction_id: str
    prediction_type: PredictionType
    level: ProcessingLevel
    value: np.ndarray
    precision: float = DEFAULT_PRECISION
    timestamp: float = field(default_factory=time.time)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class PredictionError:
    """Error between prediction and observation.

    Attributes:
        error_id: Unique identifier
        level: Processing level where error occurred
        prediction: Original prediction
        observation: Actual observation
        error: Error value (observation - prediction)
        precision_weighted_error: Error weighted by precision
        magnitude: Error magnitude
        is_anomaly: Whether error indicates anomaly
        timestamp: Detection timestamp
    """

    error_id: str
    level: ProcessingLevel
    prediction: np.ndarray
    observation: np.ndarray
    error: np.ndarray
    precision_weighted_error: np.ndarray
    magnitude: float
    is_anomaly: bool = False
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "id": self.error_id,
            "level": self.level.value,
            "magnitude": self.magnitude,
            "is_anomaly": self.is_anomaly,
        }


@dataclass
class GenerativeModel:
    """A generative model at one level of hierarchy.

    Attributes:
        level: Processing level
        weights: Model weights
        bias: Model bias
        precision: Output precision
        learning_rate: Learning rate for updates
    """

    level: ProcessingLevel
    weights: np.ndarray
    bias: np.ndarray
    precision: float = DEFAULT_PRECISION
    learning_rate: float = DEFAULT_LEARNING_RATE

    def predict(self, higher_level_state: np.ndarray) -> np.ndarray:
        """Generate prediction from higher-level state."""
        return higher_level_state @ self.weights + self.bias

    def update(self, error: np.ndarray, higher_level_state: np.ndarray) -> None:
        """Update weights based on prediction error."""
        # Gradient descent on prediction error
        grad_weights = np.outer(higher_level_state, error)
        grad_bias = error

        self.weights -= self.learning_rate * grad_weights
        self.bias -= self.learning_rate * grad_bias


@dataclass
class BeliefState:
    """Internal belief state at a hierarchy level.

    Attributes:
        level: Processing level
        mean: Belief mean (expected state)
        variance: Belief variance (uncertainty)
        precision: Inverse variance
        timestamp: Last update timestamp
    """

    level: ProcessingLevel
    mean: np.ndarray
    variance: np.ndarray
    precision: np.ndarray = field(default_factory=lambda: np.array([]))
    timestamp: float = field(default_factory=time.time)

    def __post_init__(self) -> None:
        if len(self.precision) == 0:
            self.precision = 1.0 / (self.variance + 1e-8)


@dataclass
class FreeEnergy:
    """Free energy computation result.

    Attributes:
        total: Total free energy
        prediction_error_term: Contribution from prediction errors
        complexity_term: Contribution from model complexity
        surprise: Negative log probability of observations
        entropy: Entropy of beliefs
    """

    total: float
    prediction_error_term: float
    complexity_term: float
    surprise: float = 0.0
    entropy: float = 0.0


# =============================================================================
# Precision Estimator
# =============================================================================


class PrecisionEstimator:
    """
    Estimates precision (inverse variance) of predictions.

    Precision weighting is crucial for properly combining
    predictions and observations.
    """

    def __init__(
        self,
        initial_precision: float = DEFAULT_PRECISION,
        learning_rate: float = 0.1,
        min_precision: float = 0.01,
        max_precision: float = 100.0,
    ):
        """Initialize precision estimator.

        Args:
            initial_precision: Initial precision value
            learning_rate: Learning rate for updates
            min_precision: Minimum allowed precision
            max_precision: Maximum allowed precision
        """
        self.learning_rate = learning_rate
        self.min_precision = min_precision
        self.max_precision = max_precision

        # Precision for each level
        self._precisions: dict[ProcessingLevel, float] = dict.fromkeys(
            ProcessingLevel, initial_precision
        )

        # Running error statistics
        self._error_history: dict[ProcessingLevel, deque[float]] = {
            level: deque(maxlen=100) for level in ProcessingLevel
        }

    def get_precision(self, level: ProcessingLevel) -> float:
        """Get precision for a level."""
        return self._precisions[level]

    def update_precision(
        self,
        level: ProcessingLevel,
        error_magnitude: float,
    ) -> float:
        """Update precision based on error magnitude.

        Args:
            level: Processing level
            error_magnitude: Magnitude of prediction error

        Returns:
            Updated precision
        """
        # Store error
        self._error_history[level].append(error_magnitude)

        if len(self._error_history[level]) < 10:
            return self._precisions[level]

        # Estimate variance from recent errors
        errors = np.array(self._error_history[level])
        estimated_variance = np.var(errors) + 1e-8

        # Update precision (inverse variance)
        target_precision = 1.0 / estimated_variance
        target_precision = np.clip(target_precision, self.min_precision, self.max_precision)

        # Exponential moving average
        self._precisions[level] = (1 - self.learning_rate) * self._precisions[
            level
        ] + self.learning_rate * target_precision

        return self._precisions[level]


# =============================================================================
# Hierarchical Predictive Coder
# =============================================================================


class HierarchicalPredictiveCoder:
    """
    Hierarchical predictive coding network.

    Implements multi-level predictions where each level
    predicts the activity of the level below.
    """

    def __init__(
        self,
        input_dim: int,
        hidden_dims: list[int] | None = None,
        learning_rate: float = DEFAULT_LEARNING_RATE,
    ):
        """Initialize hierarchical predictive coder.

        Args:
            input_dim: Input dimension (sensory level)
            hidden_dims: Dimensions for each hidden level
            learning_rate: Learning rate for updates
        """
        self.input_dim = input_dim
        self.hidden_dims = hidden_dims or [64, 32, 16]
        self.learning_rate = learning_rate

        # Build hierarchy
        self.levels = list(ProcessingLevel)[: len(self.hidden_dims) + 1]
        self.models: dict[ProcessingLevel, GenerativeModel] = {}
        self.beliefs: dict[ProcessingLevel, BeliefState] = {}

        self._build_hierarchy()

        # Precision estimator
        self.precision_estimator = PrecisionEstimator()

        # Error tracking
        self._error_counter = 0
        self._prediction_counter = 0

        logger.info(f"HierarchicalPredictiveCoder initialized (levels={len(self.levels)})")

    def _build_hierarchy(self) -> None:
        """Build the predictive hierarchy."""
        np.random.seed(42)

        dims = [self.input_dim] + self.hidden_dims

        for i, level in enumerate(self.levels):
            if i > 0:
                # Generative model from level i to level i-1
                input_dim = dims[i]
                output_dim = dims[i - 1]

                scale = np.sqrt(2.0 / (input_dim + output_dim))
                self.models[level] = GenerativeModel(
                    level=level,
                    weights=np.random.randn(input_dim, output_dim) * scale,
                    bias=np.zeros(output_dim),
                    learning_rate=self.learning_rate,
                )

            # Belief state for this level
            self.beliefs[level] = BeliefState(
                level=level,
                mean=np.zeros(dims[i]),
                variance=np.ones(dims[i]),
            )

    def process(
        self,
        observation: np.ndarray,
        update_beliefs: bool = True,
    ) -> tuple[list[PredictionError], FreeEnergy]:
        """Process an observation through the hierarchy.

        Args:
            observation: Input observation
            update_beliefs: Whether to update beliefs

        Returns:
            Tuple of (prediction_errors, free_energy)
        """
        prediction_errors: list[PredictionError] = []
        total_pe_magnitude = 0.0

        # Bottom-up pass: compute prediction errors
        current_input = observation

        for i, level in enumerate(self.levels):
            if i == 0:
                # Sensory level: compare with prediction from above
                if i + 1 < len(self.levels):
                    higher_level = self.levels[i + 1]
                    if higher_level in self.models:
                        prediction = self.models[higher_level].predict(
                            self.beliefs[higher_level].mean
                        )
                    else:
                        prediction = np.zeros_like(observation)
                else:
                    prediction = np.zeros_like(observation)

                error = self._compute_error(level, prediction, observation)
                prediction_errors.append(error)
                total_pe_magnitude += error.magnitude

                current_input = error.error

            else:
                # Higher levels: encode prediction error from below
                if update_beliefs:
                    self._update_belief(level, current_input)

                # Compute prediction error at this level
                if i + 1 < len(self.levels):
                    higher_level = self.levels[i + 1]
                    if higher_level in self.models:
                        prediction = self.models[higher_level].predict(
                            self.beliefs[higher_level].mean
                        )
                    else:
                        prediction = np.zeros_like(self.beliefs[level].mean)

                    error = self._compute_error(level, prediction, self.beliefs[level].mean)
                    prediction_errors.append(error)
                    total_pe_magnitude += error.magnitude

                    current_input = error.error

        # Top-down pass: update generative models
        if update_beliefs:
            self._update_models(prediction_errors)

        # Compute free energy
        free_energy = self._compute_free_energy(prediction_errors)

        return prediction_errors, free_energy

    def predict(
        self,
        steps_ahead: int = 1,
    ) -> list[Prediction]:
        """Generate predictions for future observations.

        Args:
            steps_ahead: Number of steps to predict

        Returns:
            List of predictions
        """
        predictions: list[Prediction] = []

        for _ in range(steps_ahead):
            self._prediction_counter += 1
            prediction_id = f"pred_{self._prediction_counter:06d}"

            # Propagate beliefs down the hierarchy
            for i in range(len(self.levels) - 1, 0, -1):
                level = self.levels[i]
                lower_level = self.levels[i - 1]

                if level in self.models:
                    predicted_value = self.models[level].predict(self.beliefs[level].mean)

                    precision = self.precision_estimator.get_precision(lower_level)

                    prediction = Prediction(
                        prediction_id=f"{prediction_id}_{lower_level.value}",
                        prediction_type=PredictionType.STATE,
                        level=lower_level,
                        value=predicted_value,
                        precision=precision,
                    )
                    predictions.append(prediction)

        return predictions

    def _compute_error(
        self,
        level: ProcessingLevel,
        prediction: np.ndarray,
        observation: np.ndarray,
    ) -> PredictionError:
        """Compute prediction error at a level."""
        self._error_counter += 1
        error_id = f"pe_{self._error_counter:06d}"

        error = observation - prediction
        precision = self.precision_estimator.get_precision(level)
        precision_weighted_error = precision * error

        magnitude = float(np.sqrt(np.mean(error**2)))

        # Update precision estimate
        self.precision_estimator.update_precision(level, magnitude)

        # Determine if anomaly
        is_anomaly = magnitude > 2.0 / np.sqrt(precision + 1e-8)

        return PredictionError(
            error_id=error_id,
            level=level,
            prediction=prediction,
            observation=observation,
            error=error,
            precision_weighted_error=precision_weighted_error,
            magnitude=magnitude,
            is_anomaly=is_anomaly,
        )

    def _update_belief(
        self,
        level: ProcessingLevel,
        bottom_up_signal: np.ndarray,
    ) -> None:
        """Update belief at a level."""
        belief = self.beliefs[level]

        # Get top-down prediction
        level_idx = self.levels.index(level)
        if level_idx + 1 < len(self.levels):
            higher_level = self.levels[level_idx + 1]
            if higher_level in self.models:
                top_down_prediction = self.models[higher_level].predict(
                    self.beliefs[higher_level].mean
                )
            else:
                top_down_prediction = np.zeros_like(belief.mean)
        else:
            top_down_prediction = np.zeros_like(belief.mean)

        # Precision-weighted combination of bottom-up and top-down
        bottom_up_precision = self.precision_estimator.get_precision(
            self.levels[level_idx - 1] if level_idx > 0 else level
        )
        top_down_precision = self.precision_estimator.get_precision(level)

        total_precision = bottom_up_precision + top_down_precision + 1e-8

        # Resize signals if needed
        if len(bottom_up_signal) != len(belief.mean):
            # Project or truncate
            if len(bottom_up_signal) > len(belief.mean):
                bottom_up_signal = bottom_up_signal[: len(belief.mean)]
            else:
                bottom_up_signal = np.pad(
                    bottom_up_signal,
                    (0, len(belief.mean) - len(bottom_up_signal)),
                )

        if len(top_down_prediction) != len(belief.mean):
            if len(top_down_prediction) > len(belief.mean):
                top_down_prediction = top_down_prediction[: len(belief.mean)]
            else:
                top_down_prediction = np.pad(
                    top_down_prediction,
                    (0, len(belief.mean) - len(top_down_prediction)),
                )

        # Update mean
        new_mean = (
            bottom_up_precision * bottom_up_signal + top_down_precision * top_down_prediction
        ) / total_precision

        belief.mean = (1 - self.learning_rate) * belief.mean + self.learning_rate * new_mean
        belief.timestamp = time.time()

    def _update_models(self, errors: list[PredictionError]) -> None:
        """Update generative models based on prediction errors."""
        for error in errors:
            level_idx = self.levels.index(error.level)
            if level_idx + 1 < len(self.levels):
                higher_level = self.levels[level_idx + 1]
                if higher_level in self.models:
                    self.models[higher_level].update(
                        error.error,
                        self.beliefs[higher_level].mean,
                    )

    def _compute_free_energy(
        self,
        errors: list[PredictionError],
    ) -> FreeEnergy:
        """Compute free energy from prediction errors."""
        # Prediction error term: sum of precision-weighted squared errors
        pe_term = sum(0.5 * np.sum(e.precision_weighted_error**2) for e in errors)

        # Complexity term: KL divergence from prior
        complexity_term = 0.0
        for level, belief in self.beliefs.items():
            # Assume standard normal prior
            complexity_term += 0.5 * np.sum(
                belief.mean**2 + belief.variance - 1 - np.log(belief.variance + 1e-8)
            )

        total = pe_term + complexity_term

        return FreeEnergy(
            total=float(total),
            prediction_error_term=float(pe_term),
            complexity_term=float(complexity_term),
        )


# =============================================================================
# Active Inference Agent
# =============================================================================


class ActiveInferenceAgent:
    """
    Active inference agent for anomaly detection.

    Implements active inference principles where the agent
    selects actions to minimize expected free energy.
    """

    def __init__(
        self,
        predictive_coder: HierarchicalPredictiveCoder,
        action_dim: int = 4,
    ):
        """Initialize active inference agent.

        Args:
            predictive_coder: Predictive coding network
            action_dim: Number of available actions
        """
        self.predictive_coder = predictive_coder
        self.action_dim = action_dim

        # Action preferences (prior expectations)
        self.action_prior = np.ones(action_dim) / action_dim

        # Action-outcome model
        self._action_outcomes: dict[int, list[float]] = {i: [] for i in range(action_dim)}

    def select_action(
        self,
        observation: np.ndarray,
        planning_horizon: int = 5,
    ) -> tuple[int, float]:
        """Select action to minimize expected free energy.

        Args:
            observation: Current observation
            planning_horizon: Planning horizon

        Returns:
            Tuple of (selected_action, expected_free_energy)
        """
        # Process current observation
        errors, current_fe = self.predictive_coder.process(observation)

        # Evaluate expected free energy for each action
        expected_fes = []

        for action in range(self.action_dim):
            # Simulate action consequences (simplified)
            expected_fe = self._expected_free_energy(action, errors, planning_horizon)
            expected_fes.append(expected_fe)

        # Select action with minimum expected free energy
        expected_fes = np.array(expected_fes)
        selected_action = int(np.argmin(expected_fes))

        return selected_action, float(expected_fes[selected_action])

    def _expected_free_energy(
        self,
        action: int,
        current_errors: list[PredictionError],
        horizon: int,
    ) -> float:
        """Compute expected free energy for an action.

        Expected free energy = Expected surprise + Expected divergence from preferences
        """
        # Estimate expected prediction error reduction
        avg_error = np.mean([e.magnitude for e in current_errors])

        # Historical action effectiveness
        if self._action_outcomes[action]:
            effectiveness = np.mean(self._action_outcomes[action])
        else:
            effectiveness = 0.5

        # Expected surprise (lower effectiveness = higher surprise)
        expected_surprise = avg_error * (1 - effectiveness)

        # Divergence from action prior (prefer more common actions)
        prior_divergence = -np.log(self.action_prior[action] + 1e-8)

        return expected_surprise + 0.1 * prior_divergence

    def update_from_outcome(
        self,
        action: int,
        observation: np.ndarray,
        success: bool,
    ) -> None:
        """Update models based on action outcome.

        Args:
            action: Action that was taken
            observation: Resulting observation
            success: Whether action was successful
        """
        # Record outcome
        self._action_outcomes[action].append(1.0 if success else 0.0)

        # Keep limited history
        if len(self._action_outcomes[action]) > 100:
            self._action_outcomes[action] = self._action_outcomes[action][-100:]

        # Process observation
        self.predictive_coder.process(observation, update_beliefs=True)


# =============================================================================
# Predictive Coding Anomaly Detector
# =============================================================================


class PredictiveCodingDetector:
    """
    Anomaly detector based on predictive coding principles.

    Detects anomalies as observations that generate large
    prediction errors that cannot be explained away.
    """

    def __init__(
        self,
        input_dim: int,
        hidden_dims: list[int] | None = None,
        anomaly_threshold: float = 2.0,
        learning_rate: float = DEFAULT_LEARNING_RATE,
    ):
        """Initialize predictive coding detector.

        Args:
            input_dim: Input dimension
            hidden_dims: Hidden layer dimensions
            anomaly_threshold: Threshold for anomaly detection
            learning_rate: Learning rate
        """
        self.input_dim = input_dim
        self.anomaly_threshold = anomaly_threshold

        # Predictive hierarchy
        self.coder = HierarchicalPredictiveCoder(
            input_dim=input_dim,
            hidden_dims=hidden_dims,
            learning_rate=learning_rate,
        )

        # Statistics
        self._detection_counter = 0
        self._stats = {
            "detections": 0,
            "anomalies_detected": 0,
            "avg_prediction_error": 0.0,
            "avg_free_energy": 0.0,
        }

        logger.info(f"PredictiveCodingDetector initialized (threshold={anomaly_threshold})")

    def detect(
        self,
        observation: np.ndarray,
        update_model: bool = True,
    ) -> dict[str, Any]:
        """Detect anomalies in observation.

        Args:
            observation: Input observation
            update_model: Whether to update the model

        Returns:
            Detection result
        """
        self._detection_counter += 1

        # Process through hierarchy
        errors, free_energy = self.coder.process(observation, update_beliefs=update_model)

        # Calculate overall anomaly score
        total_error = sum(e.magnitude for e in errors)
        avg_error = total_error / len(errors) if errors else 0.0

        # Anomaly score based on free energy and prediction error
        anomaly_score = self._compute_anomaly_score(errors, free_energy)

        # Determine if anomaly
        is_anomaly = anomaly_score > self.anomaly_threshold
        any_level_anomaly = any(e.is_anomaly for e in errors)

        # Update statistics
        self._stats["detections"] += 1
        if is_anomaly:
            self._stats["anomalies_detected"] += 1

        n = self._stats["detections"]
        self._stats["avg_prediction_error"] = (
            self._stats["avg_prediction_error"] * (n - 1) + avg_error
        ) / n
        self._stats["avg_free_energy"] = (
            self._stats["avg_free_energy"] * (n - 1) + free_energy.total
        ) / n

        return {
            "detection_id": f"pc_det_{self._detection_counter:06d}",
            "anomaly_score": float(anomaly_score),
            "is_anomaly": is_anomaly or any_level_anomaly,
            "confidence": 1.0 - np.exp(-anomaly_score),
            "free_energy": free_energy.total,
            "prediction_error": avg_error,
            "level_errors": [e.to_dict() for e in errors],
            "anomalous_levels": [e.level.value for e in errors if e.is_anomaly],
        }

    def _compute_anomaly_score(
        self,
        errors: list[PredictionError],
        free_energy: FreeEnergy,
    ) -> float:
        """Compute anomaly score from errors and free energy."""
        # Weight errors by level (lower levels = more important)
        weighted_error = 0.0
        total_weight = 0.0

        for i, error in enumerate(errors):
            weight = 1.0 / (i + 1)  # Higher weight for lower levels
            weighted_error += weight * error.magnitude
            total_weight += weight

        if total_weight > 0:
            avg_weighted_error = weighted_error / total_weight
        else:
            avg_weighted_error = 0.0

        # Combine with free energy
        fe_contribution = free_energy.prediction_error_term / (len(errors) + 1)

        return float(avg_weighted_error + 0.1 * fe_contribution)

    def fit(
        self,
        data: np.ndarray,
        epochs: int = 10,
    ) -> dict[str, list[float]]:
        """Fit the model to data.

        Args:
            data: Training data (n_samples, input_dim)
            epochs: Number of training epochs

        Returns:
            Training history
        """
        history = {"free_energy": [], "prediction_error": []}

        for epoch in range(epochs):
            epoch_fe = []
            epoch_pe = []

            for observation in data:
                errors, free_energy = self.coder.process(observation, update_beliefs=True)
                epoch_fe.append(free_energy.total)
                epoch_pe.append(np.mean([e.magnitude for e in errors]))

            history["free_energy"].append(float(np.mean(epoch_fe)))
            history["prediction_error"].append(float(np.mean(epoch_pe)))

            logger.info(
                f"Epoch {epoch + 1}/{epochs}: FE={history['free_energy'][-1]:.4f}, "
                f"PE={history['prediction_error'][-1]:.4f}"
            )

        return history

    def get_predictions(self, steps: int = 1) -> list[Prediction]:
        """Get future predictions.

        Args:
            steps: Steps to predict ahead

        Returns:
            List of predictions
        """
        return self.coder.predict(steps)

    def get_statistics(self) -> dict[str, Any]:
        """Get detector statistics."""
        return {
            **self._stats,
            "anomaly_threshold": self.anomaly_threshold,
            "input_dim": self.input_dim,
            "hierarchy_depth": len(self.coder.levels),
        }


# =============================================================================
# Integration with Mercury Agent
# =============================================================================


class MercuryPredictiveCoding:
    """
    Predictive coding integration for Mercury Agent.

    Provides neuroscience-inspired anomaly detection
    as part of the Mercury Agent framework.
    """

    def __init__(
        self,
        input_dim: int = 64,
        hidden_dims: list[int] | None = None,
        anomaly_threshold: float = 2.0,
        enable_active_inference: bool = True,
    ):
        """Initialize Mercury predictive coding.

        Args:
            input_dim: Input dimension
            hidden_dims: Hidden layer dimensions
            anomaly_threshold: Anomaly detection threshold
            enable_active_inference: Enable active inference actions
        """
        self.detector = PredictiveCodingDetector(
            input_dim=input_dim,
            hidden_dims=hidden_dims,
            anomaly_threshold=anomaly_threshold,
        )

        self.enable_active_inference = enable_active_inference

        if enable_active_inference:
            self.agent = ActiveInferenceAgent(
                self.detector.coder,
                action_dim=4,  # investigate, monitor, alert, ignore
            )

        # Action names
        self._actions = ["investigate", "monitor", "alert", "ignore"]

    def analyze(
        self,
        features: np.ndarray,
        return_action: bool = False,
    ) -> dict[str, Any]:
        """Analyze features for anomalies.

        Args:
            features: Input features
            return_action: Whether to return recommended action

        Returns:
            Analysis result
        """
        # Detect anomaly
        detection = self.detector.detect(features)

        result = {
            "anomaly_score": detection["anomaly_score"],
            "is_anomaly": detection["is_anomaly"],
            "confidence": detection["confidence"],
            "free_energy": detection["free_energy"],
            "prediction_error": detection["prediction_error"],
        }

        # Get recommended action via active inference
        if return_action and self.enable_active_inference:
            action_idx, expected_fe = self.agent.select_action(features)
            result["recommended_action"] = self._actions[action_idx]
            result["action_confidence"] = np.exp(-expected_fe)

        return result

    def train(
        self,
        data: np.ndarray,
        epochs: int = 10,
    ) -> dict[str, list[float]]:
        """Train the predictive model.

        Args:
            data: Training data
            epochs: Training epochs

        Returns:
            Training history
        """
        return self.detector.fit(data, epochs)

    def get_statistics(self) -> dict[str, Any]:
        """Get module statistics."""
        return {
            "detector": self.detector.get_statistics(),
            "active_inference_enabled": self.enable_active_inference,
        }
