"""
Mercury Agent Copyright (C) 2025 Steel Security Advisors LLC.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see https://www.gnu.org/licenses/.

------------------------------------------------------------------------

Operator tool: emit the Lyapunov convergence proof block as LaTeX
directly into ``docs/MATH_SPEC.md``.

Given the certificate parameters ``(A, P, λ)`` — system matrix,
Lyapunov matrix, and contractual decay rate — the tool derives the
corresponding proof statement and writes it inside a sentinelled
section of ``docs/MATH_SPEC.md``::

    <!-- CONVERGENCE-PROOF:BEGIN -->
    ...generated LaTeX...
    <!-- CONVERGENCE-PROOF:END -->

Anything outside that pair of sentinels is left untouched.  The
sentinels match the convention used by the existing benchmark block
in ``README.md`` so the same drift-gate tooling (CI markdown lint,
pre-commit hooks) covers both files.

The single source-of-truth for the proof bound is this tool — any
human edit between the sentinels is overwritten on the next run, by
design, so the certificate cannot diverge from the documented proof.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
from pathlib import Path
from typing import Any

import numpy as np

from omni_mercury_engine.tools._base import Certificate, run_tool

_SCHEMA = "mercury.tools.convergence_proof_emitter/v1"
_BEGIN = "<!-- CONVERGENCE-PROOF:BEGIN -->"
_END = "<!-- CONVERGENCE-PROOF:END -->"
_REPO_ROOT = Path(__file__).resolve().parents[3]
_DEFAULT_DOC = _REPO_ROOT / "docs" / "MATH_SPEC.md"


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m omni_mercury_engine.tools.convergence_proof_emitter",
        description=(
            "Derive the Lyapunov convergence-rate proof from (A, P, λ) and "
            "splice the LaTeX block into docs/MATH_SPEC.md between sentinels."
        ),
    )
    parser.add_argument(
        "--A",
        default=None,
        help=(
            "Path to .npy file containing the (n x n) system matrix A. "
            "If omitted, the canonical Mercury fusion linearisation is used."
        ),
    )
    parser.add_argument(
        "--P",
        default=None,
        help="Path to .npy file containing the (n x n) Lyapunov matrix P (default I).",
    )
    parser.add_argument(
        "--lambda",
        dest="lambda_",
        type=float,
        default=None,
        help="Override LYAPUNOV.LAMBDA_CONVERGENCE.",
    )
    parser.add_argument(
        "--doc",
        default=str(_DEFAULT_DOC),
        help="Markdown file to update (default docs/MATH_SPEC.md).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compute the block but do NOT write the doc; exit non-zero if it differs.",
    )
    return parser


def _canonical_A() -> np.ndarray:
    """Return the canonical 3x3 fusion linearisation matrix.

    A = -lambda * I — the simplest Lyapunov-stable linearisation that
    realises the Mercury contract V(t) <= eps*exp(-lambda*t) exactly.
    Operators with a non-trivial system matrix supply ``--A``.
    """
    from omni_mercury_engine.core.centralized_constants import LYAPUNOV

    lam = float(LYAPUNOV.LAMBDA_CONVERGENCE)
    return -lam * np.eye(3, dtype=np.float64)


def _render_latex(
    A: np.ndarray,
    P: np.ndarray,
    lam: float,
    Q: np.ndarray,
    Q_min_eig: float,
    P_max_eig: float,
    bound_rate: float,
) -> str:
    """Render the proof block as LaTeX-friendly Markdown."""

    def _matrix(name: str, mat: np.ndarray) -> str:
        rows = " \\\\ ".join(
            " & ".join(f"{v:+.6f}" for v in row.tolist()) for row in mat
        )
        return f"{name} = \\begin{{bmatrix}} {rows} \\end{{bmatrix}}"

    now = _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")
    return (
        f"<!-- Auto-generated by omni_mercury_engine.tools.convergence_proof_emitter "
        f"at {now}. Do not edit by hand; edits between the sentinels are overwritten. -->\n"
        f"\n"
        f"### Convergence proof (auto-derived)\n"
        f"\n"
        f"Given the candidate Lyapunov function $V(x) = x^\\top P x$ with\n"
        f"\n"
        f"$$\n{_matrix('P', P)}\n$$\n"
        f"\n"
        f"and the closed-loop system $\\dot x = A x$ where\n"
        f"\n"
        f"$$\n{_matrix('A', A)},\n$$\n"
        f"\n"
        f"the Lyapunov derivative is $\\dot V(x) = x^\\top Q x$ with\n"
        f"$Q = A^\\top P + P A$:\n"
        f"\n"
        f"$$\n{_matrix('Q', Q)}.\n$$\n"
        f"\n"
        f"Numerical eigenvalue analysis (binary64) gives\n"
        f"$\\lambda_{{\\min}}(-Q) = {Q_min_eig:.6f}$ and\n"
        f"$\\lambda_{{\\max}}(P)  = {P_max_eig:.6f}$,\n"
        f"so the contraction rate is\n"
        f"\n"
        f"$$\n"
        f"\\dot V(x) \\le -\\frac{{\\lambda_{{\\min}}(-Q)}}"
        f"{{\\lambda_{{\\max}}(P)}} V(x) = -{bound_rate:.6f}\\, V(x).\n"
        f"$$\n"
        f"\n"
        f"Integrating gives the exponential bound\n"
        f"\n"
        f"$$\n"
        f"V(S_t) \\le V(S_0)\\,\\exp(-\\lambda\\, t),\\quad \\lambda = {lam:.6f},\n"
        f"$$\n"
        f"\n"
        f"matching the contractual rate `LYAPUNOV.LAMBDA_CONVERGENCE = {lam:.6f}` "
        f"declared in `core/centralized_constants.py`.\n"
    )


def _splice(doc: Path, block: str) -> tuple[str, str]:
    """Return (old, new) doc contents after splicing ``block`` between sentinels.

    If the sentinels are absent, append a new sentinelled section at
    the end of the document.
    """
    if doc.exists():
        old = doc.read_text()
    else:
        old = ""
    if _BEGIN in old and _END in old:
        pattern = re.compile(
            re.escape(_BEGIN) + r".*?" + re.escape(_END),
            flags=re.DOTALL,
        )
        new = pattern.sub(f"{_BEGIN}\n{block}\n{_END}", old)
    else:
        sep = "" if old.endswith("\n") else "\n"
        new = f"{old}{sep}\n## Convergence proof\n\n{_BEGIN}\n{block}\n{_END}\n"
    return old, new


def _collect(args: argparse.Namespace) -> Certificate:
    from omni_mercury_engine.core.centralized_constants import LYAPUNOV

    lam = float(args.lambda_) if args.lambda_ is not None else float(LYAPUNOV.LAMBDA_CONVERGENCE)
    A = np.load(args.A, allow_pickle=False) if args.A else _canonical_A()
    if args.P:
        P = np.load(args.P, allow_pickle=False)
    else:
        P = np.eye(A.shape[0], dtype=np.float64)

    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError(f"A must be square, got shape {A.shape}")
    if P.shape != A.shape:
        raise ValueError(f"P shape {P.shape} != A shape {A.shape}")

    Q = A.T @ P + P @ A
    # ``-Q`` is the contraction matrix; its smallest eigenvalue lower-bounds
    # the decay rate via the Rayleigh quotient.
    Q_eigs = np.linalg.eigvalsh(-(Q + Q.T) / 2.0)  # symmetrise for eigvalsh
    P_eigs = np.linalg.eigvalsh((P + P.T) / 2.0)
    Q_min_eig = float(Q_eigs.min())
    P_max_eig = float(P_eigs.max())
    if P_max_eig <= 0.0:
        raise ValueError("P is not positive-definite; cannot bound V(t)")
    bound_rate = Q_min_eig / P_max_eig

    block = _render_latex(A, P, lam, Q, Q_min_eig, P_max_eig, bound_rate)
    doc = Path(args.doc)
    old, new = _splice(doc, block)

    body: dict[str, Any] = {
        "doc": str(doc),
        "lambda": lam,
        "matrix_size": int(A.shape[0]),
        "Q_min_eig": Q_min_eig,
        "P_max_eig": P_max_eig,
        "derived_bound_rate": bound_rate,
        "matches_contract": bound_rate + 1e-9 >= lam,
        "block_chars": len(block),
        "check_only": bool(args.check),
        "changed": new != old,
    }

    warnings: list[str] = []
    if not body["matches_contract"]:
        warnings.append(
            f"derived bound rate {bound_rate:.6f} is below the contractual lambda {lam:.6f}"
        )

    if args.check:
        status = "ok" if not body["changed"] else "fail"
        if status == "fail":
            warnings.append("docs/MATH_SPEC.md is out of sync with the derived proof block")
        return Certificate(
            tool="convergence_proof_emitter",
            schema=_SCHEMA,
            status=status,
            body=body,
            warnings=warnings,
        )

    doc.parent.mkdir(parents=True, exist_ok=True)
    doc.write_text(new)
    return Certificate(
        tool="convergence_proof_emitter",
        schema=_SCHEMA,
        status="ok" if body["matches_contract"] else "warn",
        body=body,
        warnings=warnings,
    )


def main(argv: list[str] | None = None) -> int:
    """CLI entry-point."""
    return run_tool(_build_parser, _collect, argv)


if __name__ == "__main__":
    raise SystemExit(main())
