# Copyright (C) 2025 Steel Security Advisors LLC
"""(at your option) any later version."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any

import numpy as np
import numpy.typing as npt

from omni_mercury_engine.tools._base import Certificate, atomic_write_text, run_tool

_SCHEMA = "mercury.tools.convergence_proof_emitter/v1"
_BEGIN = "<!-- CONVERGENCE-PROOF:BEGIN -->"
_END = "<!-- CONVERGENCE-PROOF:END -->"
_REPO_ROOT = Path(__file__).resolve().parents[3]
_DEFAULT_DOC = _REPO_ROOT / "docs" / "MATH_SPEC.md"


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m omni_mercury_engine.tools.convergence_proof_emitter",
        description=(
            "Derive the Lyapunov convergence-rate proof from (A, P, λ) and "
            "splice the LaTeX block into docs/MATH_SPEC.md between sentinels."
        ),
    )
    parser.add_argument(
        "--A",
        default=None,
        help=(
            "Path to .npy file containing the (n x n) system matrix A. "
            "If omitted, the canonical Mercury fusion linearisation is used."
        ),
    )
    parser.add_argument(
        "--P",
        default=None,
        help="Path to .npy file containing the (n x n) Lyapunov matrix P (default I).",
    )
    parser.add_argument(
        "--lambda",
        dest="lambda_",
        type=float,
        default=None,
        help="Override LYAPUNOV.LAMBDA_CONVERGENCE.",
    )
    parser.add_argument(
        "--doc",
        default=str(_DEFAULT_DOC),
        help="Markdown file to update (default docs/MATH_SPEC.md).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compute the block but do NOT write the doc; exit non-zero if it differs.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Render the block and report what would change, but do NOT write the doc.",
    )
    return parser


def _canonical_A() -> npt.NDArray[np.float64]:
    """Return the canonical 3x3 fusion linearisation matrix.

    A = -lambda * I — the simplest Lyapunov-stable linearisation that
    realises the Mercury contract V(t) <= eps*exp(-lambda*t) exactly.
    Operators with a non-trivial system matrix supply ``--A``.
    """
    from omni_mercury_engine.core.centralized_constants import LYAPUNOV

    lam = float(LYAPUNOV.LAMBDA_CONVERGENCE)
    return -lam * np.eye(3, dtype=np.float64)


def _render_latex(
    A: npt.NDArray[np.float64],
    P: npt.NDArray[np.float64],
    lam: float,
    Q: npt.NDArray[np.float64],
    Q_min_eig: float,
    P_max_eig: float,
    bound_rate: float,
) -> str:
    """Render the proof block as LaTeX-friendly Markdown."""

    def _matrix(name: str, mat: npt.NDArray[np.float64]) -> str:
        rows = " \\\\ ".join(" & ".join(f"{v:+.6f}" for v in row.tolist()) for row in mat)
        return f"{name} = \\begin{{bmatrix}} {rows} \\end{{bmatrix}}"

    return (
        f"<!-- Auto-generated by omni_mercury_engine.tools.convergence_proof_emitter. "
        f"Do not edit by hand; edits between the sentinels are overwritten. -->\n"
        f"\n"
        f"### Convergence proof (auto-derived)\n"
        f"\n"
        f"Given the candidate Lyapunov function $V(x) = x^\\top P x$ with\n"
        f"\n"
        f"$$\n{_matrix('P', P)}\n$$\n"
        f"\n"
        f"and the closed-loop system $\\dot x = A x$ where\n"
        f"\n"
        f"$$\n{_matrix('A', A)},\n$$\n"
        f"\n"
        f"the Lyapunov derivative is $\\dot V(x) = x^\\top Q x$ with\n"
        f"$Q = A^\\top P + P A$:\n"
        f"\n"
        f"$$\n{_matrix('Q', Q)}.\n$$\n"
        f"\n"
        f"Numerical eigenvalue analysis (binary64) gives\n"
        f"$\\lambda_{{\\min}}(-Q) = {Q_min_eig:.6f}$ and\n"
        f"$\\lambda_{{\\max}}(P)  = {P_max_eig:.6f}$,\n"
        f"so the contraction rate is\n"
        f"\n"
        f"$$\n"
        f"\\dot V(x) \\le -\\frac{{\\lambda_{{\\min}}(-Q)}}"
        f"{{\\lambda_{{\\max}}(P)}} V(x) = -{bound_rate:.6f}\\, V(x).\n"
        f"$$\n"
        f"\n"
        f"Integrating gives the exponential bound\n"
        f"\n"
        f"$$\n"
        f"V(S_t) \\le V(S_0)\\,\\exp(-\\lambda\\, t),\\quad \\lambda = {lam:.6f},\n"
        f"$$\n"
        f"\n"
        f"matching the contractual rate `LYAPUNOV.LAMBDA_CONVERGENCE = {lam:.6f}` "
        f"declared in `core/centralized_constants.py`.\n"
    )


class _SentinelError(ValueError):
    """Raised when MATH_SPEC.md has malformed sentinels (one without the other)."""


def _splice(doc: Path, block: str) -> tuple[str, str]:
    """Return (old, new) doc contents after splicing ``block`` between sentinels.

    Contract:

    * If **both** sentinels are present, replace only the bytes
      strictly between them.  Bytes outside the sentinels are preserved
      byte-for-byte (no trailing-newline drift, no whitespace
      normalisation).
    * If **neither** sentinel is present, append a fresh sentinelled
      section at the end of the doc.
    * If **exactly one** sentinel is present the doc is malformed and we
      fail loud — silently writing a second copy of the block would
      corrupt the doc.
    * Idempotent: repeated runs with the same ``block`` produce
      byte-identical output.
    """
    old = doc.read_text() if doc.exists() else ""
    has_begin = _BEGIN in old
    has_end = _END in old
    if has_begin ^ has_end:
        raise _SentinelError(
            f"{doc}: one sentinel present but not the other "
            f"(BEGIN={has_begin}, END={has_end}); refusing to splice"
        )
    if has_begin and has_end:
        # Multiple BEGIN/END pairs would also be malformed; require
        # exactly one each.
        if old.count(_BEGIN) != 1 or old.count(_END) != 1:
            raise _SentinelError(
                f"{doc}: sentinels must appear exactly once each "
                f"(BEGIN={old.count(_BEGIN)}, END={old.count(_END)})"
            )
        pattern = re.compile(
            re.escape(_BEGIN) + r".*?" + re.escape(_END),
            flags=re.DOTALL,
        )
        # ``re.sub`` interprets backslash sequences in the replacement
        # string; LaTeX contains literal ``\eta``/``\lambda`` so we use a
        # callable replacement to bypass backreference parsing.
        replacement = f"{_BEGIN}\n{block}\n{_END}"
        new = pattern.sub(lambda _m: replacement, old)
    else:
        sep = "" if old.endswith("\n") or old == "" else "\n"
        new = f"{old}{sep}\n## Convergence proof\n\n{_BEGIN}\n{block}\n{_END}\n"
    return old, new


def _collect(args: argparse.Namespace) -> Certificate:
    from omni_mercury_engine.core.centralized_constants import LYAPUNOV

    lam = float(args.lambda_) if args.lambda_ is not None else float(LYAPUNOV.LAMBDA_CONVERGENCE)
    A = np.load(args.A, allow_pickle=False) if args.A else _canonical_A()
    if args.P:
        P = np.load(args.P, allow_pickle=False)
    else:
        P = np.eye(A.shape[0], dtype=np.float64)

    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError(f"A must be square, got shape {A.shape}")
    if P.shape != A.shape:
        raise ValueError(f"P shape {P.shape} != A shape {A.shape}")

    Q = A.T @ P + P @ A
    # ``-Q`` is the contraction matrix; its smallest eigenvalue lower-bounds
    # the decay rate via the Rayleigh quotient.
    Q_eigs = np.linalg.eigvalsh(-(Q + Q.T) / 2.0)  # symmetrise for eigvalsh
    P_eigs = np.linalg.eigvalsh((P + P.T) / 2.0)
    Q_min_eig = float(Q_eigs.min())
    P_max_eig = float(P_eigs.max())
    if P_max_eig <= 0.0:
        raise ValueError("P is not positive-definite; cannot bound V(t)")
    bound_rate = Q_min_eig / P_max_eig

    block = _render_latex(A, P, lam, Q, Q_min_eig, P_max_eig, bound_rate)
    doc = Path(args.doc)
    try:
        old, new = _splice(doc, block)
    except _SentinelError as exc:
        return Certificate(
            tool="convergence_proof_emitter",
            schema=_SCHEMA,
            status="fail",
            body={
                "doc": str(doc),
                "error": "malformed_sentinels",
                "detail": str(exc),
            },
            warnings=[str(exc)],
        )

    body: dict[str, Any] = {
        "doc": str(doc),
        "lambda": lam,
        "matrix_size": int(A.shape[0]),
        "Q_min_eig": Q_min_eig,
        "P_max_eig": P_max_eig,
        "derived_bound_rate": bound_rate,
        "matches_contract": bound_rate + 1e-9 >= lam,
        "block_chars": len(block),
        "check_only": bool(args.check),
        "changed": new != old,
    }

    warnings: list[str] = []
    if not body["matches_contract"]:
        warnings.append(
            f"derived bound rate {bound_rate:.6f} is below the contractual lambda {lam:.6f}"
        )

    if args.check or args.dry_run:
        body["dry_run"] = bool(args.dry_run)
        status = "ok" if not body["changed"] else ("fail" if args.check else "warn")
        if body["changed"]:
            warnings.append(
                f"{doc} is out of sync with the derived proof block ("
                f"--check would fail; --dry-run would write)"
            )
        return Certificate(
            tool="convergence_proof_emitter",
            schema=_SCHEMA,
            status=status,
            body=body,
            warnings=warnings,
        )

    atomic_write_text(doc, new)
    return Certificate(
        tool="convergence_proof_emitter",
        schema=_SCHEMA,
        status="ok" if body["matches_contract"] else "warn",
        body=body,
        warnings=warnings,
    )


def main(argv: list[str] | None = None) -> int:
    """CLI entry-point."""
    return run_tool(_build_parser, _collect, argv)


if __name__ == "__main__":
    raise SystemExit(main())
