"""
Mercury Agent Copyright (C) 2025 Steel Security Advisors LLC.

This program is free software: you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not,
see https://www.gnu.org/licenses/.
"""

from __future__ import annotations

"""Measure — and *enforce* — the Mercury Agent codebase-scale numbers.

This script is the single source of truth for the structural counts that
the README advertises.  It reports, all measured from what is actually on
disk (never hand-typed):

  * source files and SLOC under ``src/omni_mercury_engine``,
  * top-level *Python packages* (a directory is only counted if it holds an
    ``__init__.py`` — this excludes ``__pycache__``, ``*.egg-info`` and any
    hidden directory, which the previous implementation wrongly counted),
  * detector classes (``class *Detector``) under ``detectors/``,
  * data-loader classes (``class *Loader``) under ``loaders/``,
  * test files and test SLOC,
  * ``import torch`` / ``from torch`` modules and ``class …(nn.Module)``
    definitions,
  * GitHub Actions workflow files.

It has no third-party dependencies, so it runs in any CI environment
without installing the Mercury Agent package.

Modes
-----
    python scripts/measure_codebase_scale.py            # human table
    python scripts/measure_codebase_scale.py --json     # machine JSON
    python scripts/measure_codebase_scale.py --check README.md
        # exit 0 if the README scale block matches the measured numbers,
        # exit 1 (printing a diff) if it has drifted.  This is the CI gate
        # that makes doc/code divergence impossible to merge.
    python scripts/measure_codebase_scale.py --update README.md
        # rewrite the README scale block in place from the measured numbers.

The README block is delimited by the ``<!-- SCALE:START -->`` and
``<!-- SCALE:END -->`` HTML comments so the rendered numbers stay
deterministic and machine-regenerable.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "omni_mercury_engine"
TESTS = ROOT / "tests"
DETECTORS = SRC / "detectors"
LOADERS = SRC / "loaders"
WORKFLOWS = ROOT / ".github" / "workflows"

TORCH_IMPORT_RE = re.compile(r"^\s*(?:from\s+torch\b|import\s+torch\b)", re.MULTILINE)
NN_MODULE_RE = re.compile(r"^\s*class\s+\w+\([^)]*\bnn\.Module\b[^)]*\):", re.MULTILINE)
DETECTOR_CLASS_RE = re.compile(r"^class\s+\w*Detector\b", re.MULTILINE)
LOADER_CLASS_RE = re.compile(r"^class\s+\w*Loader\b", re.MULTILINE)

# LOC figures are advertised as approximate (the ``~`` prefix) order-of-
# magnitude scale, not exact line tallies.  Rounding them to the nearest
# ``LOC_BUCKET`` keeps the CI drift gate stable under routine churn — adding a
# few lines to one test must not force a README regeneration — while still
# surfacing real structural growth.  Discrete counts (files, packages, classes,
# workflows) are exact and never bucketed; those are the signal the original
# rewrite was protecting (e.g. the 512→603 source-file drift).
LOC_BUCKET = 1000

SCALE_START = "<!-- SCALE:START -->"
SCALE_END = "<!-- SCALE:END -->"
# Stamped into the generated block so readers know how to regenerate it.
SCALE_PROVENANCE = (
    "_Generated by `python scripts/measure_codebase_scale.py --update README.md` "
    "and gated in CI (`scripts/measure_codebase_scale.py --check README.md`); "
    "do not hand-edit between the markers._"
)


def _round_loc(loc: int) -> int:
    """Bucket an LOC count to the nearest ``LOC_BUCKET`` for stable display.

    The README advertises LOC with a ``~`` prefix; bucketing makes the drift
    gate insensitive to small, routine line churn while still tracking real
    growth (any net change of at least half a bucket moves the figure).
    """
    return int(round(loc / LOC_BUCKET) * LOC_BUCKET)


def _count_lines(paths: list[Path]) -> int:
    total = 0
    for p in paths:
        try:
            with p.open("r", encoding="utf-8", errors="replace") as fh:
                for _ in fh:
                    total += 1
        except OSError:
            continue
    return total


def _is_package_dir(path: Path) -> bool:
    """A directory counts as a subpackage only if it is a real Python package.

    Excludes ``__pycache__``, hidden directories (``.foo``) and build
    artifacts such as ``*.egg-info`` — none of which are importable
    subpackages, even though the old ``p.is_dir()`` check counted them.
    """
    if not path.is_dir():
        return False
    name = path.name
    if name.startswith(".") or name == "__pycache__" or name.endswith(".egg-info"):
        return False
    return (path / "__init__.py").exists()


def _count_class_matches(directory: Path, pattern: re.Pattern[str]) -> int:
    if not directory.is_dir():
        return 0
    total = 0
    for p in sorted(directory.rglob("*.py")):
        try:
            total += len(pattern.findall(p.read_text(encoding="utf-8", errors="replace")))
        except OSError:
            continue
    return total


def measure() -> dict[str, object]:
    src_files = sorted(SRC.rglob("*.py")) if SRC.is_dir() else []
    test_files = sorted(TESTS.rglob("test_*.py")) if TESTS.is_dir() else []
    subpackages = (
        sorted(p.name for p in SRC.iterdir() if _is_package_dir(p)) if SRC.is_dir() else []
    )
    workflows = sorted(p.name for p in WORKFLOWS.glob("*.yml")) if WORKFLOWS.is_dir() else []

    torch_files = 0
    nn_module_classes = 0
    for p in src_files:
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if TORCH_IMPORT_RE.search(text):
            torch_files += 1
        nn_module_classes += len(NN_MODULE_RE.findall(text))

    return {
        "src_files": len(src_files),
        "src_loc": _count_lines(src_files),
        "subpackages": subpackages,
        "subpackage_count": len(subpackages),
        "detector_classes": _count_class_matches(DETECTORS, DETECTOR_CLASS_RE),
        "loader_classes": _count_class_matches(LOADERS, LOADER_CLASS_RE),
        "test_files": len(test_files),
        "test_loc": _count_lines(test_files),
        "torch_importing_files": torch_files,
        "nn_module_subclasses": nn_module_classes,
        "workflow_count": len(workflows),
    }


def render_block(stats: dict[str, object]) -> str:
    """Render the deterministic README scale block (between the markers)."""
    rows = [
        ("Python source files in `src/omni_mercury_engine/`", f"**{stats['src_files']}**"),
        ("Source lines of code (LOC)", f"**~{_round_loc(int(stats['src_loc'])):,}**"),
        (
            "Top-level subpackages (true Python packages with `__init__.py`)",
            f"**{stats['subpackage_count']}**",
        ),
        (
            "Files importing PyTorch (optional `[ml]` extra)",
            f"**{stats['torch_importing_files']}**",
        ),
        ("Distinct `torch.nn.Module` subclasses", f"**{stats['nn_module_subclasses']}**"),
        (
            "Detector classes (`class *Detector`) in `detectors/`",
            f"**{stats['detector_classes']}**",
        ),
        ("Data-loader classes (`class *Loader`) in `loaders/`", f"**{stats['loader_classes']}**"),
        (
            "Test modules (`test_*.py`) / total test LOC",
            f"**{stats['test_files']} modules / ~{_round_loc(int(stats['test_loc'])):,} LOC**",
        ),
        ("GitHub Actions workflows", f"**{stats['workflow_count']}**"),
    ]
    lines = [SCALE_START, "", "| Measurement | Value |", "|---|---|"]
    lines += [f"| {label} | {value} |" for label, value in rows]
    lines += ["", SCALE_PROVENANCE, "", SCALE_END]
    return "\n".join(lines)


def _splice(readme_text: str, new_block: str) -> str:
    start = readme_text.index(SCALE_START)
    end = readme_text.index(SCALE_END) + len(SCALE_END)
    return readme_text[:start] + new_block + readme_text[end:]


def _extract_block(readme_text: str) -> str:
    start = readme_text.index(SCALE_START)
    end = readme_text.index(SCALE_END) + len(SCALE_END)
    return readme_text[start:end]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of a table.")
    parser.add_argument(
        "--check",
        metavar="README",
        help="Verify the README scale block matches measured numbers (CI gate).",
    )
    parser.add_argument(
        "--update", metavar="README", help="Rewrite the README scale block in place."
    )
    args = parser.parse_args(argv)

    stats = measure()

    if args.check or args.update:
        readme_path = Path(args.check or args.update)
        try:
            text = readme_path.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"ERROR: cannot read {readme_path}: {exc}", file=sys.stderr)
            return 2
        if SCALE_START not in text or SCALE_END not in text:
            print(
                f"ERROR: {readme_path} is missing the {SCALE_START} / {SCALE_END} markers.",
                file=sys.stderr,
            )
            return 2
        expected = render_block(stats)
        if args.update:
            readme_path.write_text(_splice(text, expected), encoding="utf-8")
            print(f"Updated scale block in {readme_path}.")
            return 0
        current = _extract_block(text)
        if current.strip() == expected.strip():
            print(f"OK: {readme_path} scale block is up to date.")
            return 0
        print(
            f"DRIFT: {readme_path} scale block is stale. "
            "Run `python scripts/measure_codebase_scale.py --update README.md`.\n"
            "--- measured (expected) ---\n"
            f"{expected}\n"
            "--- README (current) ---\n"
            f"{current}",
            file=sys.stderr,
        )
        return 1

    if args.json:
        json.dump(stats, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
        return 0

    print("Mercury Agent — measured codebase scale")
    print("---------------------------------------")
    print(f"src files:                {stats['src_files']}")
    print(f"src LOC:                  {int(stats['src_loc']):,}")
    print(f"subpackages:              {stats['subpackage_count']}")
    print(f"detector classes:         {stats['detector_classes']}")
    print(f"loader classes:           {stats['loader_classes']}")
    print(f"test files:               {stats['test_files']}")
    print(f"test LOC:                 {int(stats['test_loc']):,}")
    print(f"torch-importing files:    {stats['torch_importing_files']}")
    print(f"nn.Module subclasses:     {stats['nn_module_subclasses']}")
    print(f"workflows:                {stats['workflow_count']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
